name: mxc_application
description: Application Framework in the MVC Design Pattern using plugins and packages prior to the AndroidX migration.
version: 2.0.3
author: Greg Perry <support@andrioussolutions.com>
homepage: https://github.com/AndriousSolutions/mxc_application
repository: https://github.com/AndriousSolutions/mxc_application

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # https://pub.dartlang.org/packages/mvc_pattern#-changelog-tab-
  mvc_pattern: ^3.3.6
#      path: ../../packages/mvc_pattern

  # https://pub.dartlang.org/packages/connectivity#-changelog-tab-
  connectivity: ^0.3.0

  # https://pub.dartlang.org/packages/sqflite#-changelog-tab-
  sqflite: 1.0.0

  # https://pub.dartlang.org/packages/url_launcher#-changelog-tab-
  url_launcher: ^4.1.0

  # https://pub.dartlang.org/packages/package_info#-changelog-tab-
  package_info: ^0.3.2

  # https://pub.dartlang.org/packages/device_info#-changelog-tab-
  device_info: ^0.3.0

  # https://pub.dartlang.org/packages/flutter_material_color_picker#-changelog-tab-
  flutter_material_color_picker: ^0.0.5

  # https://pub.dartlang.org/packages/path_provider#-changelog-tab-
  path_provider: ^0.4.0

  # https://pub.dartlang.org/packages/uuid#-changelog-tab-
  uuid: ^2.0.0

  # https://pub.dartlang.org/packages/prefs#-changelog-tab-
  prefs: ^3.0.0

  # https://pub.dartlang.org/packages/xml#-changelog-tab-
  xml: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

# To add assets to your package, add an assets section, like this:
# assets:
#  - images/a_dot_burr.jpeg
#  - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.io/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.io/assets-and-images/#resolution-aware.

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.io/custom-fonts/#from-packages
